CREATE DATABASE IF NOT EXISTS lordaeron_website
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE lordaeron_website;

CREATE TABLE IF NOT EXISTS news (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title_en VARCHAR(255) NOT NULL,
  title_fr VARCHAR(255) NOT NULL DEFAULT '',
  title_es VARCHAR(255) NOT NULL DEFAULT '',
  title_de VARCHAR(255) NOT NULL DEFAULT '',
  title_it VARCHAR(255) NOT NULL DEFAULT '',
  content_en TEXT NOT NULL,
  content_fr TEXT NOT NULL,
  content_es TEXT NOT NULL,
  content_de TEXT NOT NULL,
  content_it TEXT NOT NULL,
  image_url VARCHAR(512) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS soul_shards (
  account_id INT UNSIGNED NOT NULL PRIMARY KEY,
  balance INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
